### PR TITLE
Removes fallback code from eStore integration

### PR DESCRIPTION
**Pull request by dikiyforester**
Addition to previous PR

### CODE REVIEW

**Comment by Arsenal21** [comment]
Don't use that code since that exists primarily for WP eStore's backward compatibility reason. For The WPEC plugin this shouldn't be an issue. So that plugin should be able to just call the following function as is (it shouldn't need that fallfack):

SLM_API_Utility::insert_license_data_internal()

I don't really want to introduce that fallback for ALL other plugins that maybe using this function to insert. In the future, when I refactor estore's code, I will likely remove that fallback from there and call the above function directly.

**Comment by dikiyforester** [comment]
I'm not sure how this relates to eStore compatibility, but you probably need to revert https://github.com/Arsenal21/software-license-manager/pull/24 as it adds the fallback to the SLM_API_Utility::insert_license_data_internal() method.

**Comment by Arsenal21** [comment]
That fallback is only done for the estore integration because back in the day when estore was receiving IPN, sometimes it wasn't getting things in UTF-8 formatting. That was causing issue, this fallback was a fix for that.

Why should that be an issue with WPEC plugin you think? So why should we introduce this fallback for any other code calling the following function?

SLM_API_Utility::insert_license_data_internal()

**Comment by dikiyforester** [comment]
Ok, thanks for explanations!

**Pull request closed without merging**
